services:
  pg:
    image: postgres:latest
    env_file:
      - ./.env
    container_name: pg
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server --protected-mode no --bind 0.0.0.0
    env_file:
      - ./.env
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: on-failure
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:5540"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis
    

volumes:
  pg_data:
  redis_data:
  redisinsight_data:
